# Configuration for a Dark Forest universe
# Defined in TOML as per https://toml.io/en/v0.5.0

[initializers]
START_PAUSED = true
ADMIN_CAN_ADD_PLANETS = true
TOKEN_MINT_END_TIMESTAMP = 2022-03-01T05:00:00.000Z
WORLD_RADIUS_LOCKED = false

##################################
# SNARK keys & Perlin parameters #
##################################
DISABLE_ZK_CHECKS = false
PLANETHASH_KEY = 115
SPACETYPE_KEY = 116
BIOMEBASE_KEY = 117
PERLIN_MIRROR_X = false
PERLIN_MIRROR_Y = false
PERLIN_LENGTH_SCALE = 16384 # must be a power of two no greater than 16384

##############
# Space junk #
##############
SPACE_JUNK_ENABLED = true
# Total amount of space junk a player can take on. This can be overridden at runtime by updating this value for a specific player in storage.
SPACE_JUNK_LIMIT = 2000
# The amount of junk that each level of planet gives the player when moving to it for the first time.
PLANET_LEVEL_JUNK = [20, 25, 30, 35, 40, 45, 50, 55, 60, 65]
# The speed boost a movement receives when abandoning a planet.
ABANDON_SPEED_CHANGE_PERCENT = 150
# The range boost a movement receives when abandoning a planet.
ABANDON_RANGE_CHANGE_PERCENT = 150

##############
# Capture zones #
##############
CAPTURE_ZONES_ENABLED = true
# How often zones change location. Max 255.
CAPTURE_ZONE_CHANGE_BLOCK_INTERVAL = 255
# How big the capture zones are
CAPTURE_ZONE_RADIUS = 1000
# The amount of score each planet level gives for capturing
CAPTURE_ZONE_PLANET_LEVEL_SCORE = [
  0,
  0,
  250_000,
500_000,
  750_000,
