# Configuration for a Dark Forest universe
# Defined in TOML as per https://toml.io/en/v0.5.0

[initializers]
START_PAUSED = true
ADMIN_CAN_ADD_PLANETS = true
TOKEN_MINT_END_TIMESTAMP = 2022-03-01T05:00:00.000Z
WORLD_RADIUS_LOCKED = false

##################################
# SNARK keys & Perlin parameters #
##################################
DISABLE_ZK_CHECKS = false
PLANETHASH_KEY = 115
SPACETYPE_KEY = 116
BIOMEBASE_KEY = 117
PERLIN_MIRROR_X = false
PERLIN_MIRROR_Y = false
PERLIN_LENGTH_SCALE = 16384 # must be a power of two no greater than 16384

##############
# Space junk #
##############
SPACE_JUNK_ENABLED = true
# Total amount of space junk a player can take on. This can be overridden at runtime by updating this value for a specific player in storage.
