# Configuration for a Dark Forest universe
# Defined in TOML as per https://toml.io/en/v0.5.0

[initializers]
START_PAUSED = true
ADMIN_CAN_ADD_PLANETS = true
TOKEN_MINT_END_TIMESTAMP = 2022-03-01T05:00:00.000Z
WORLD_RADIUS_LOCKED = false

##################################
# SNARK keys & Perlin parameters #
##################################
DISABLE_ZK_CHECKS = false
PLANETHASH_KEY = 115
SPACETYPE_KEY = 116
BIOMEBASE_KEY = 117
